# Created by L.S. Urrea [lurreaferia@uniminuto.edu.co], J. Sanchez-Rojas [jsanchezro8@uniminuto.edu.co], & C.A.Sierra [carlos.andres.sierra.v@gmail.com] on May 2019.

# Collaboration acknowlegments: María Fernanda Chaparro & Fernando Alvarez & Santiago Salazar.

# Copyright (c) 2019 L.S. Urrea, J. Sanchez-Rojas, & C.A.Sierra. Research Group on Athenea. All rights reserved.

#

# This file is part of RaspXbee Project.

#

# RaspXbee Project is free software: you can redistribute it and/or modify it under the terms of the

# GNU General Public License as published by the Free Software Foundation, version 3
# Generated by Django 2.1.5 on 2019-02-10 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ether_Conex_Gate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ethernet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModoConex', models.CharField(max_length=50)),
                ('Estado', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Gate_Nodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GateWay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=45)),
                ('LatCoord', models.CharField(max_length=45)),
                ('LongCoord', models.CharField(max_length=45)),
                ('Estado', models.CharField(max_length=45)),
                ('localAddress', models.CharField(max_length=150)),
                ('ForeingAddress', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ip', models.CharField(max_length=45)),
                ('Temperatura', models.CharField(max_length=45)),
                ('Voltaje', models.CharField(max_length=45)),
                ('Estado', models.CharField(max_length=45)),
                ('LatCoord', models.CharField(max_length=45)),
                ('LongCoord', models.CharField(max_length=45)),
                ('Mac', models.CharField(max_length=45)),
                ('Dir_16Bits', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Sim_Conex_Gate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FK_idGateWay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCode.GateWay')),
            ],
        ),
        migrations.CreateModel(
            name='SimCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=150)),
                ('Operador', models.CharField(max_length=45)),
                ('CardPin', models.CharField(max_length=45)),
                ('UserSim', models.CharField(max_length=45)),
                ('PasswordSim', models.CharField(max_length=45)),
                ('Estado', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Wifi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Direccion', models.CharField(max_length=150)),
                ('MascaraRed', models.CharField(max_length=150)),
                ('BroadCast', models.CharField(max_length=150)),
                ('Dns_1', models.CharField(max_length=150)),
                ('Dns_2', models.CharField(max_length=150)),
                ('Protocolo', models.CharField(max_length=150)),
                ('Canal', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Wifi_Conex_Gate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FK_idGateWay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCode.GateWay')),
                ('FK_idWifi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCode.Wifi')),
            ],
        ),
        migrations.AddField(
            model_name='sim_conex_gate',
            name='FK_idSimCard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCode.SimCard'),
        ),
        migrations.AddField(
            model_name='gate_nodo',
            name='FK_idGateWay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCode.GateWay'),
        ),
        migrations.AddField(
            model_name='gate_nodo',
            name='FK_idNodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCode.Nodo'),
        ),
        migrations.AddField(
            model_name='ether_conex_gate',
            name='FK_idEthernet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCode.Ethernet'),
        ),
        migrations.AddField(
            model_name='ether_conex_gate',
            name='FK_idGateWay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCode.GateWay'),
        ),
    ]
