# Created by L.S. Urrea [lurreaferia@uniminuto.edu.co], J. Sanchez-Rojas [jsanchezro8@uniminuto.edu.co], & C.A.Sierra [carlos.andres.sierra.v@gmail.com] on May 2019.

# Collaboration acknowlegments: María Fernanda Chaparro & Fernando Alvarez & Santiago Salazar.

# Copyright (c) 2019 L.S. Urrea, J. Sanchez-Rojas, & C.A.Sierra. Research Group on Athenea. All rights reserved.

#

# This file is part of RaspXbee Project.

#

# RaspXbee Project is free software: you can redistribute it and/or modify it under the terms of the

# GNU General Public License as published by the Free Software Foundation, version 3
# Generated by Django 2.1.5 on 2019-05-18 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCode', '0003_auto_20190413_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethernet',
            name='gateway_fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='appCode.Gateway'),
        ),
        migrations.AlterField(
            model_name='node',
            name='address_16bits',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='node',
            name='ip',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='node',
            name='mac',
            field=models.CharField(default='None', max_length=25),
        ),
        migrations.AlterField(
            model_name='node',
            name='state_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appCode.States_Node'),
        ),
        migrations.AlterField(
            model_name='node_gateway',
            name='gateway_fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='appCode.Gateway'),
        ),
        migrations.AlterField(
            model_name='simcard',
            name='gateway_fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='appCode.Gateway'),
        ),
        migrations.AlterField(
            model_name='wifi_gateway',
            name='gateway_fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='appCode.Gateway'),
        ),
    ]
