# Created by L.S. Urrea [lurreaferia@uniminuto.edu.co], J. Sanchez-Rojas [jsanchezro8@uniminuto.edu.co], & C.A.Sierra [carlos.andres.sierra.v@gmail.com] on May 2019.

# Collaboration acknowlegments: María Fernanda Chaparro & Fernando & Santiago Salazar.

# Copyright (c) 2019 L.S. Urrea, J. Sanchez-Rojas, & C.A.Sierra. Research Group on Athenea. All rights reserved.

#

# This file is part of RaspXbee Project.

#

# RaspXbee Project is free software: you can redistribute it and/or modify it under the terms of the

# GNU General Public License as published by the Free Software Foundation, version 3
# Generated by Django 2.1.2 on 2019-04-13 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCode', '0002_auto_20190413_1626'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=25, unique=True)),
                ('description', models.CharField(default='None', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Conection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_conn', models.DateTimeField(auto_now=True)),
                ('ethernet_fk', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='appCode.Ethernet')),
                ('simcard_fk', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='appCode.Simcard')),
            ],
        ),
        migrations.CreateModel(
            name='User_App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pssword', models.CharField(default='None', max_length=50)),
                ('email', models.EmailField(default='None', max_length=50, unique=True)),
                ('phone', models.CharField(default='None', max_length=15)),
                ('nickname', models.OneToOneField(default='None', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='conexion',
            name='FK_idEthernet',
        ),
        migrations.RemoveField(
            model_name='conexion',
            name='FK_idSimCard',
        ),
        migrations.RemoveField(
            model_name='conexion',
            name='FK_idUsuario',
        ),
        migrations.RemoveField(
            model_name='conexion',
            name='FK_idWifi',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='Nombre',
        ),
        migrations.RemoveField(
            model_name='log',
            name='Accion',
        ),
        migrations.RemoveField(
            model_name='log',
            name='Donde',
        ),
        migrations.RemoveField(
            model_name='log',
            name='FK_idUsuario',
        ),
        migrations.RemoveField(
            model_name='log',
            name='Fecha',
        ),
        migrations.AddField(
            model_name='log',
            name='date_log',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Conexion',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='conection',
            name='usuario_fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='usuario.User_App'),
        ),
        migrations.AddField(
            model_name='conection',
            name='wifi_fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='appCode.Wifi'),
        ),
        migrations.AddField(
            model_name='log',
            name='action',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='usuario.Action_Log'),
        ),
        migrations.AddField(
            model_name='log',
            name='user_fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='usuario.User_App'),
        ),
    ]
