# Generated by Django 2.1.5 on 2019-05-18 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20190413_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conection',
            name='simcard_fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='appCode.Simcard'),
        ),
    ]
